spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: flowabledev
    url: jdbc:mysql://172.17.150.112:3306/flowabledev?characterEncoding=UTF-8
    username: flowabledev
server:
  port: 8989
